export const STORE_AUTH = 'STORE_AUTH';
export const GET_HEART_RATE = 'GET_HEART_RATE';
export const GET_HEART_RATE_SUCCESS = 'GET_HEART_RATE_SUCCESS';
export const GET_HEART_RATE_FAILURE = 'GET_HEART_RATE_FAILURE';
